FROM python:3.12-slim 
#Creamos carpeta de trabajo del contenedor.
WORKDIR /app

#Copiamos los requerimientos del servidor (. el punto se refiere a la carpeta de trabajo del contenedor).
COPY requirements.txt . 

#Instalamos los requerimientos.
RUN pip install --no-cache-dir -r requirements.txt

#Copiar el codigo del API
COPY ./app ./app

#Exponer el puerto
EXPOSE 5000

#Comando de ejecucion FASTAPI 0.0.0.0 Es correspondiente a localhosts.
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]

#Espeficicaciones para el contenedor y crear la imagen del API.


